<?php

namespace App\Libraries;

use CodeIgniter\Database\BaseConnection;

class DatabaseInitializer
{
    public function ensure(BaseConnection $db): void
    {
        if ($db->tableExists('customer_accounts') && $db->tableExists('user_accounts') && $db->tableExists('users')) {
            return;
        }

        $db->transStart();

        $db->query(<<<'SQL'
CREATE TABLE IF NOT EXISTS customer_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(50) NOT NULL UNIQUE,
    customer_name VARCHAR(150) NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(100),
    meter_number VARCHAR(50),
    connection_type VARCHAR(20) NOT NULL DEFAULT 'residential' CHECK (connection_type IN ('residential', 'commercial', 'industrial')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
SQL);

        $db->query("CREATE INDEX IF NOT EXISTS idx_account_number ON customer_accounts (account_number)");
        $db->query("CREATE INDEX IF NOT EXISTS idx_status ON customer_accounts (status)");
        $db->query("CREATE INDEX IF NOT EXISTS idx_connection_type ON customer_accounts (connection_type)");
        $db->query("CREATE INDEX IF NOT EXISTS idx_customer_name ON customer_accounts (customer_name)");

        $db->query(<<<'SQL'
CREATE TABLE IF NOT EXISTS user_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
)
SQL);

        $db->query(<<<'SQL'
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(10),
    password VARCHAR(255) NOT NULL,
    user_type VARCHAR(20) DEFAULT 'customer',
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
)
SQL);

        $exists = $db->query("SELECT 1 FROM user_accounts WHERE username = 'demoTeacher' LIMIT 1")->getRowArray();
        if (! $exists) {
            $db->table('user_accounts')->insert([
                'username' => 'demoTeacher',
                'password' => 'demoPassword',
            ]);
        }

        $customerCount = (int) ($db->query('SELECT COUNT(*) AS count FROM customer_accounts')->getRow()->count ?? 0);
        if ($customerCount === 0) {
            $customers = [
                ['account_number'=>'EC-2024-0001','customer_name'=>'John Smith','address'=>'123 Main Street, Downtown','phone'=>'555-0101','email'=>'john.smith@email.com','meter_number'=>'MTR-001','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0002','customer_name'=>'Sarah Johnson','address'=>'456 Oak Avenue, Suburb','phone'=>'555-0102','email'=>'sarah.j@email.com','meter_number'=>'MTR-002','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0003','customer_name'=>'ABC Corporation','address'=>'789 Business Blvd, City Center','phone'=>'555-0103','email'=>'contact@abc.com','meter_number'=>'MTR-003','connection_type'=>'commercial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0004','customer_name'=>'Michael Brown','address'=>'321 Pine Road, Eastside','phone'=>'555-0104','email'=>'mbrown@email.com','meter_number'=>'MTR-004','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0005','customer_name'=>'Tech Industries Inc','address'=>'555 Industrial Park, Zone A','phone'=>'555-0105','email'=>'info@techindustries.com','meter_number'=>'MTR-005','connection_type'=>'industrial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0006','customer_name'=>'Emily Davis','address'=>'678 Maple Drive, Westside','phone'=>'555-0106','email'=>'emily.d@email.com','meter_number'=>'MTR-006','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0007','customer_name'=>'Green Mart Store','address'=>'890 Commerce Street, Plaza','phone'=>'555-0107','email'=>'greenmart@email.com','meter_number'=>'MTR-007','connection_type'=>'commercial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0008','customer_name'=>'Robert Wilson','address'=>'234 Cedar Lane, Northside','phone'=>'555-0108','email'=>'rwilson@email.com','meter_number'=>'MTR-008','connection_type'=>'residential','status'=>'inactive','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0009','customer_name'=>'Manufacturing Co','address'=>'432 Factory Road, Industrial Zone','phone'=>'555-0109','email'=>'info@mfgco.com','meter_number'=>'MTR-009','connection_type'=>'industrial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0010','customer_name'=>'Lisa Anderson','address'=>'567 Birch Street, Southside','phone'=>'555-0110','email'=>'landerson@email.com','meter_number'=>'MTR-010','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0011','customer_name'=>'David Martinez','address'=>'890 Elm Avenue, Central','phone'=>'555-0111','email'=>'dmartinez@email.com','meter_number'=>'MTR-011','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0012','customer_name'=>'Retail Plaza LLC','address'=>'123 Shopping Center, Mall District','phone'=>'555-0112','email'=>'contact@retailplaza.com','meter_number'=>'MTR-012','connection_type'=>'commercial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0013','customer_name'=>'Jennifer Taylor','address'=>'456 Spruce Road, Hillside','phone'=>'555-0113','email'=>'jtaylor@email.com','meter_number'=>'MTR-013','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0014','customer_name'=>'Heavy Industries Ltd','address'=>'789 Manufacturing Ave, Zone B','phone'=>'555-0114','email'=>'info@heavyind.com','meter_number'=>'MTR-014','connection_type'=>'industrial','status'=>'suspended','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0015','customer_name'=>'Thomas White','address'=>'321 Willow Lane, Riverside','phone'=>'555-0115','email'=>'twhite@email.com','meter_number'=>'MTR-015','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0016','customer_name'=>'Office Complex Inc','address'=>'654 Corporate Drive, Business Park','phone'=>'555-0116','email'=>'admin@officecomplex.com','meter_number'=>'MTR-016','connection_type'=>'commercial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0017','customer_name'=>'Patricia Harris','address'=>'987 Ash Street, Lakeside','phone'=>'555-0117','email'=>'pharris@email.com','meter_number'=>'MTR-017','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0018','customer_name'=>'Auto Manufacturing','address'=>'246 Assembly Line Rd, Industrial Park','phone'=>'555-0118','email'=>'contact@automfg.com','meter_number'=>'MTR-018','connection_type'=>'industrial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0019','customer_name'=>'Christopher Lee','address'=>'135 Poplar Avenue, Garden District','phone'=>'555-0119','email'=>'clee@email.com','meter_number'=>'MTR-019','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0020','customer_name'=>'Shopping Center Co','address'=>'468 Retail Blvd, Downtown','phone'=>'555-0120','email'=>'info@shopcenter.com','meter_number'=>'MTR-020','connection_type'=>'commercial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0021','customer_name'=>'Nancy Clark','address'=>'579 Hickory Drive, Parkside','phone'=>'555-0121','email'=>'nclark@email.com','meter_number'=>'MTR-021','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0022','customer_name'=>'Steel Works Inc','address'=>'802 Foundry Road, Industrial Zone C','phone'=>'555-0122','email'=>'contact@steelworks.com','meter_number'=>'MTR-022','connection_type'=>'industrial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0023','customer_name'=>'Daniel Lewis','address'=>'913 Sycamore Lane, Meadow View','phone'=>'555-0123','email'=>'dlewis@email.com','meter_number'=>'MTR-023','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0024','customer_name'=>'Restaurant Group LLC','address'=>'246 Dining Street, Food District','phone'=>'555-0124','email'=>'info@restgroup.com','meter_number'=>'MTR-024','connection_type'=>'commercial','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
                ['account_number'=>'EC-2024-0025','customer_name'=>'Karen Walker','address'=>'357 Magnolia Road, Sunset Hills','phone'=>'555-0125','email'=>'kwalker@email.com','meter_number'=>'MTR-025','connection_type'=>'residential','status'=>'active','created_at'=>'2025-10-22 01:01:51','updated_at'=>'2025-10-22 01:01:51'],
            ];

            $db->table('customer_accounts')->insertBatch($customers);
        }

        $db->transComplete();

        if (! $db->transStatus()) {
            throw new \RuntimeException('Unable to initialize the Render PostgreSQL database.');
        }
    }
}
